# Enabling mouse
set -g mouse on

# Set Prefix 
#bind C-b
#set -g prefix C-Space
#bind C-Space send-prefix

# in copy mode use vim motions style
setw -g mode-keys vi

# Remap horizontal and vertical splits
bind-key -n C-E split-window -h -c "#{pane_current_path}" 
bind-key -n C-O split-window -v -c "#{pane_current_path}"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin "janoamaral/tokyo-night-tmux"

# Icon styles
set -g @tokyo-night-tmux_terminal_icon 
set -g @tokyo-night-tmux_active_terminal_icon 

# No extra spaces between icons
set -g @tokyo-night-tmux_window_tidy_icons 0

set -g @tokyo-night-tmux_window_id_style digital
set -g @tokyo-night-tmux_pane_id_style hsquare
set -g @tokyo-night-tmux_zoom_id_style dsquare

run ~/.tmux/plugins/tpm/tpm
